# Generated by Django 3.0.4 on 2021-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'entities_entity',
                'managed': False,
            },
        ),
    ]
